// Code generated by protoc-gen-go.
// source: spaxos.proto
// DO NOT EDIT!

/*
Package spaxospb is a generated protocol buffer package.

syntax = "proto2";

It is generated from these files:
	spaxos.proto

It has these top-level messages:
	PaxosEntry
	Message
*/
package spaxospb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessageType int32

const (
	MessageType_MsgHup  MessageType = 0
	MessageType_MsgBeat MessageType = 1
	// # Prop
	MessageType_MsgProp     MessageType = 2
	MessageType_MsgPropResp MessageType = 3
	// # Accpt
	MessageType_MsgAccpt     MessageType = 4
	MessageType_MsgAccptResp MessageType = 5
)

var MessageType_name = map[int32]string{
	0: "MsgHup",
	1: "MsgBeat",
	2: "MsgProp",
	3: "MsgPropResp",
	4: "MsgAccpt",
	5: "MsgAccptResp",
}
var MessageType_value = map[string]int32{
	"MsgHup":       0,
	"MsgBeat":      1,
	"MsgProp":      2,
	"MsgPropResp":  3,
	"MsgAccpt":     4,
	"MsgAccptResp": 5,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

type PaxosEntry struct {
	PropNum          *uint64 `protobuf:"varint,1,opt,name=propNum" json:"propNum,omitempty"`
	AccptNum         *uint64 `protobuf:"varint,2,opt,name=accptNum" json:"accptNum,omitempty"`
	Value            []byte  `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PaxosEntry) Reset()         { *m = PaxosEntry{} }
func (m *PaxosEntry) String() string { return proto.CompactTextString(m) }
func (*PaxosEntry) ProtoMessage()    {}

func (m *PaxosEntry) GetPropNum() uint64 {
	if m != nil && m.PropNum != nil {
		return *m.PropNum
	}
	return 0
}

func (m *PaxosEntry) GetAccptNum() uint64 {
	if m != nil && m.AccptNum != nil {
		return *m.AccptNum
	}
	return 0
}

func (m *PaxosEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Message struct {
	Type             *MessageType `protobuf:"varint,1,opt,name=type,enum=spaxospb.MessageType" json:"type,omitempty"`
	To               *uint64      `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	From             *uint64      `protobuf:"varint,3,opt,name=from" json:"from,omitempty"`
	Index            *uint64      `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	Entry            *PaxosEntry  `protobuf:"bytes,5,opt,name=entry" json:"entry,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetType() MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MessageType_MsgHup
}

func (m *Message) GetTo() uint64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

func (m *Message) GetFrom() uint64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *Message) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Message) GetEntry() *PaxosEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterEnum("spaxospb.MessageType", MessageType_name, MessageType_value)
}
